repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-xml
    - id: check-yaml
    - id: detect-private-key
    - id: debug-statements
    - id: end-of-file-fixer
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      additional_dependencies:
        - flake8-bugbear
        - flake8-comprehensions
        - flake8-simplify
        - flake8-isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    - id: mypy
